# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_detail', models.TextField(blank=True, max_length=1000, null=True)),
                ('name', models.TextField(blank=True, max_length=1000, null=True)),
                ('box', jsonfield.fields.JSONField(blank=True, null=True)),
                ('polyLines', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
